version: '2'
#
# I had to use 
#       network_mode: "host"
# because the communication between the participating services and also the redirects to integrate 
# the resource owner is based on "localhost" which I did not want to change.
#
# BUT: it seems that this network mode is not working on MacOS (and maybe Windows).
#      see https://github.com/docker/for-mac/issues/1031
# 
services:
    client:
        image: mobi3006/oauth2-in-action
        build: .
        network_mode: "host"
        command: node client.js
    authorization-server:
        image: mobi3006/oauth2-in-action
        build: .
        network_mode: "host"
        command: node authorizationServer.js
    protected-resource:
        image: mobi3006/oauth2-in-action
        build: .
        network_mode: "host"
        command: node protectedResource.js
             