version: '2'

# I had to use 
#       network_mode: "host"
# because the communication between the participating services and also the redirects to integrate 
# the resource owner is based on "localhost" which I did not want to change.

services:
    client:
        image: mobi3006/oauth-in-action
        build: .
        network_mode: "host"
        ports:
             - "9000:9000"
        command: node client.js
    authorization-server:
        image: mobi3006/oauth-in-action
        build: .
        network_mode: "host"
        ports:
             - "9001:9001"
        command: node authorizationServer.js
    protected-resource:
        image: mobi3006/oauth-in-action
        build: .
        network_mode: "host"
        ports:
             - "9002:9002"
        command: node protectedResource.js
             